apiVersion: v1
kind: ConfigMap
metadata:
  name: retailstore-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "retailstore.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.aspnetcoreEnvironment | quote }}
  ASPNETCORE_URLS: "http://+:8080"
  Jwt__Issuer: {{ .Values.config.jwtIssuer | quote }}
  Jwt__Audience: {{ .Values.config.jwtAudience | quote }}
  Jwt__ExpiryInMinutes: {{ .Values.config.jwtExpiryMinutes | quote }}
  Seed__AdminEmail: {{ .Values.config.seedAdminEmail | quote }}
  ACCEPT_EULA: "Y"
  MSSQL_PID: "Developer"
